#!/usr/bin/env bash
# CyberKiller - one-command self-host.
#
#   ./deploy.sh            bring the range up (generates .env on first run)
#   ./deploy.sh update     pull latest, rebuild, restart (keeps data)
#   ./deploy.sh teardown   stop everything cleanly (keeps data + images)
#   ./deploy.sh delete     remove everything: containers, target images, volumes (DB included)
#
# Requirements: Docker + the compose plugin. Nothing else - the Go API is built
# inside a container, so you do not need Go installed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"
GO_IMAGE="golang:1.24-bookworm"

c_info() { printf '\033[0;36m[ck]\033[0m %s\n' "$*"; }
c_ok()   { printf '\033[0;32m[ok]\033[0m %s\n' "$*"; }
c_die()  { printf '\033[0;31m[!!]\033[0m %s\n' "$*" >&2; exit 1; }

compose() { docker compose --env-file "$ENV_FILE" "$@"; }

need_docker() {
  command -v docker >/dev/null 2>&1 || c_die "Docker is not installed. Install Docker + the compose plugin first."
  docker compose version >/dev/null 2>&1 || c_die "The Docker compose plugin is missing (need 'docker compose')."
  docker info >/dev/null 2>&1 || c_die "Cannot talk to the Docker daemon. Is it running, and can this user reach it?"
}

gen_env() {
  [ -f "$ENV_FILE" ] && { c_ok ".env already exists - using it"; return; }
  c_info "Generating .env ..."
  # Use the host's LAN/primary IP - NOT the public IP. This is a lab range that
  # should never be internet-facing, and players reach it on the local network.
  local ip
  ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  [ -n "$ip" ] || ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [ -n "$ip" ] || ip="localhost"
  local admin_pass invite
  admin_pass="$(openssl rand -hex 12)"
  invite="$(openssl rand -hex 6)"

  # Arena network: try LAN mode (ipvlan - each target gets a real LAN IP, reachable
  # from any machine with no routing) when we can detect a usable parent interface
  # + subnet; otherwise fall back to a private bridge (host-local). The operator can
  # override any of these in .env.
  local a_parent a_cidr a_gw a_prefix a_mode
  a_parent="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
  a_cidr="$(ip -o -f inet addr show "$a_parent" 2>/dev/null | awk '{print $4; exit}')"   # e.g. 192.168.1.129/24
  a_gw="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="via"){print $(i+1); exit}}')"
  a_prefix="$(echo "${a_cidr%/*}" | awk -F. '{print $1"."$2"."$3}')"
  if [ -n "$a_parent" ] && [ -n "$a_prefix" ] && [ -n "$a_gw" ] && [ "${a_cidr#*/}" = "24" ]; then
    a_mode="lan"   # targets at <prefix>.200-.223 on the physical LAN (block .192/27)
  else
    a_mode="bridge"
    a_prefix="10.66.20"; a_gw=""; a_parent=""
  fi
  local a_base; [ "$a_mode" = "lan" ] && a_base=200 || a_base=50
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh. Edit freely, then re-run ./deploy.sh.
POSTGRES_PASSWORD=$(openssl rand -hex 20)
JWT_SECRET=$(openssl rand -hex 32)

# Admin panel login (reach the panel via SSH tunnel to 127.0.0.1:3001).
ADMIN_USER=admin
ADMIN_PASS=${admin_pass}

# Where players reach the API + hub. Defaults to this host's IP on port 3000/8080.
# If you put it behind a domain + TLS, set these to your https URL.
API_URL=http://${ip}:8080
CORS_ORIGINS=http://${ip}:3000,http://localhost:3000

# Player signup. Open signup with a shared invite code, or set SIGNUP_OPEN=false.
SIGNUP_OPEN=true
SIGNUP_INVITE_CODE=${invite}

# Ship the bundled MERIDIAN example scenario (10-box Linux breach chain).
CORP_ORCHESTRATION=true
MAX_ACTIVE_HILLS=5

# Arena network. lan = targets get real LAN IPs (ipvlan on ARENA_PARENT) so any
# machine on the LAN reaches them with no routing. bridge = private 10.66.20.0/24,
# reachable from the host only (good for a single host / cloud VPS).
ARENA_MODE=${a_mode}
ARENA_PARENT=${a_parent}
# Must be the network address, not the host IP: Docker rejects a --subnet with
# host bits set (e.g. 192.168.1.129/24), which would silently kill LAN/ipvlan mode.
# Derive it from the /24 prefix so it is always the .0 network address.
ARENA_SUBNET=${a_prefix}.0/24
ARENA_GATEWAY=${a_gw}
ARENA_IP_PREFIX=${a_prefix}
ARENA_BOX_BASE=${a_base}

# Port bindings. Admin stays on localhost on purpose.
API_BIND=8080
WEB_BIND=3000
ADMIN_BIND=127.0.0.1:3001
EOF
  c_ok ".env generated (admin: admin / ${admin_pass} - invite code: ${invite})"
}

build_api() {
  c_info "Building the API binary (in a container) ..."
  mkdir -p "$ROOT/build"
  docker run --rm -v "$ROOT":/src -w /src/api "$GO_IMAGE" \
    go build -buildvcs=false -o /src/build/cyberkiller-api ./cmd/server
  c_ok "API binary built"
}

build_targets() {
  c_info "Building target images (CVE bases + the MERIDIAN example) ..."
  bash "$ROOT/local/build-all-target-images.sh"
  if grep -q '^CORP_ORCHESTRATION=true' "$ENV_FILE"; then
    bash "$ROOT/local/build-corp-images.sh"
  fi
  c_ok "Target images built"
}

# refresh_host_ip keeps the baked LAN address current. gen_env only writes the
# host IP on first run, so moving this machine to another network (laptop hops
# WiFi, DHCP lease changes) leaves a stale API_URL/CORS_ORIGINS and players can no
# longer reach the hub. On every `up` we re-detect the primary IP and, when the
# baked URL is a plain http://<private-LAN-IP> that no longer matches, rewrite it.
# Custom domains and https:// configs are left untouched.
refresh_host_ip() {
  [ -f "$ENV_FILE" ] || return 0
  local cur_url cur_ip cur_re new_ip
  cur_url="$(grep -E '^API_URL=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"
  case "$cur_url" in http://*) ;; *) return 0 ;; esac   # only manage plain-http URLs
  cur_ip="${cur_url#http://}"; cur_ip="${cur_ip%%:*}"
  # Only refresh when the baked host is an RFC1918 LAN IP - never a domain or localhost.
  case "$cur_ip" in
    10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[01].*) ;;
    *) return 0 ;;
  esac
  new_ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  [ -n "$new_ip" ] || return 0
  [ "$new_ip" = "$cur_ip" ] && return 0
  c_info "Host IP changed ($cur_ip -> $new_ip) - refreshing API_URL + CORS_ORIGINS in .env."
  cur_re="${cur_ip//./\\.}"
  sed -i -E "/^(API_URL|CORS_ORIGINS)=/ s/${cur_re}/${new_ip}/g" "$ENV_FILE"
}

# ensure_arena_network creates the ck-arena network per ARENA_MODE before compose
# runs. lan -> ipvlan L2 on the physical NIC (real LAN IPs, no routing); bridge ->
# private 10.66.20.0/24. Idempotent; recreates only if the driver changed and no
# containers are attached. Falls back to bridge if ipvlan can't be set up.
ensure_arena_network() {
  local mode parent subnet gw prefix want cur
  # Each read tolerates a missing key: grep exits non-zero when the var is absent,
  # which under `set -e` + pipefail would kill the whole script - and an older .env
  # that predates the ARENA_* block is the common case. `|| true` keeps us going.
  mode="$(grep -E '^ARENA_MODE=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"; [ -z "$mode" ] && mode="bridge"
  parent="$(grep -E '^ARENA_PARENT=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"
  subnet="$(grep -E '^ARENA_SUBNET=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"
  gw="$(grep -E '^ARENA_GATEWAY=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"
  prefix="$(grep -E '^ARENA_IP_PREFIX=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)"; [ -z "$prefix" ] && prefix="10.66.20"
  [ "$mode" = "lan" ] && want="ipvlan" || want="bridge"

  cur="$(docker network inspect ck-arena --format '{{.Driver}}' 2>/dev/null || true)"
  if [ -n "$cur" ] && [ "$cur" != "$want" ]; then
    c_info "Recreating ck-arena ($cur -> $want) ..."
    docker network rm ck-arena >/dev/null 2>&1 || c_die "ck-arena is in use - run ./deploy.sh teardown first."
    cur=""
  fi
  [ -n "$cur" ] && { c_ok "ck-arena network ready ($cur)"; return; }

  if [ "$mode" = "lan" ] && docker network create -d ipvlan \
        --subnet "$subnet" --gateway "$gw" --ip-range "${prefix}.192/27" \
        -o parent="$parent" -o ipvlan_mode=l2 ck-arena >/dev/null 2>&1; then
    c_ok "ck-arena (LAN/ipvlan on ${parent}) - targets get real LAN IPs ${prefix}.200-.223"
    return
  fi
  if [ "$mode" = "lan" ]; then
    c_info "ipvlan unavailable here (WiFi/cloud?) - falling back to bridge mode."
    sed -i 's/^ARENA_MODE=.*/ARENA_MODE=bridge/; s/^ARENA_IP_PREFIX=.*/ARENA_IP_PREFIX=10.66.20/; s/^ARENA_BOX_BASE=.*/ARENA_BOX_BASE=50/' "$ENV_FILE"
  fi
  docker network create -d bridge --subnet 10.66.20.0/24 ck-arena >/dev/null 2>&1
  c_ok "ck-arena (bridge 10.66.20.0/24) ready"
}

cmd_up() {
  need_docker
  gen_env
  refresh_host_ip
  ensure_arena_network
  build_api
  build_targets
  c_info "Building + starting the control stack ..."
  compose build
  compose up -d
  c_info "Waiting for the API to become healthy ..."
  local i
  for i in $(seq 1 40); do
    if curl -sf "http://localhost:$(grep -E '^API_BIND=' "$ENV_FILE" | cut -d= -f2 | tr -d ' ')/health" >/dev/null 2>&1; then
      c_ok "API healthy"
      break
    fi
    sleep 2
    [ "$i" -eq 40 ] && c_die "API did not come up. Check: docker logs ck-control"
  done
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  echo
  c_ok "CyberKiller is up."
  echo "  Hub:    ${API_URL%/api}" | sed 's#:8080#:3000#'
  echo "  Admin:  ssh -L 3001:127.0.0.1:3001 <this-host>, then http://localhost:3001  (login: ${ADMIN_USER})"
  echo "  Invite: ${SIGNUP_INVITE_CODE}"
  if [ "${ARENA_MODE:-bridge}" = "lan" ]; then
    echo "  Targets: ${ARENA_IP_PREFIX}.200-.223 on your LAN - nmap from any machine (no routing). MERIDIAN live if enabled."
  else
    echo "  Targets: ${ARENA_IP_PREFIX:-10.66.20}.50-59 - nmap them from this host. MERIDIAN live if enabled."
  fi
}

# cmd_update pulls the latest code, rebuilds, and brings the stack back up. Data
# (the Postgres volume) is preserved. One command to update a running range.
cmd_update() {
  if [ -d "$ROOT/.git" ]; then
    # Only pull when the current branch tracks a remote (the normal clone case).
    # A branch with no upstream - e.g. a local dev branch - can't `git pull`; warn
    # and rebuild from the working tree rather than aborting the update.
    if git -C "$ROOT" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' >/dev/null 2>&1; then
      c_info "Pulling latest code..."
      git -C "$ROOT" pull --ff-only || c_die "git pull failed (stash/commit local changes first)"
    else
      c_info "Branch has no upstream - skipping pull, rebuilding from the current tree."
    fi
  fi
  c_info "Rebuilding + restarting (data preserved)..."
  cmd_up
}

cmd_teardown() {
  need_docker
  c_info "Stopping the control stack ..."
  [ -f "$ENV_FILE" ] && compose down || docker rm -f ck-control ck-web ck-admin ck-db ck-redis 2>/dev/null || true
  c_info "Stopping any live target containers ..."
  docker ps -aq --filter network=ck-arena | xargs -r docker rm -f >/dev/null 2>&1 || true
  c_ok "Everything stopped. Data + images kept. Run ./deploy.sh to bring it back."
}

cmd_delete() {
  need_docker
  printf '\033[0;31mThis removes ALL containers, target images, and volumes (including the database). Type DELETE to confirm: \033[0m'
  read -r ans
  [ "$ans" = "DELETE" ] || { echo "aborted"; exit 0; }
  [ -f "$ENV_FILE" ] && compose down -v --remove-orphans || true
  docker ps -aq --filter network=ck-arena | xargs -r docker rm -f >/dev/null 2>&1 || true
  docker network rm ck-arena >/dev/null 2>&1 || true
  c_info "Removing CyberKiller images ..."
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E '^cyberkiller/' | xargs -r docker rmi -f >/dev/null 2>&1 || true
  c_ok "Pruned. (.env kept - delete it by hand to reset credentials.)"
}

case "${1:-up}" in
  up|"")    cmd_up ;;
  update)   cmd_update ;;
  teardown) cmd_teardown ;;
  delete)   cmd_delete ;;
  *) c_die "usage: ./deploy.sh [up|update|teardown|delete]" ;;
esac
