[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:devdash]
command=/usr/bin/python3 /opt/devdash/devdash.py
user=devweb
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
