[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:jenkins]
command=/bin/bash -c "/usr/local/bin/jenkins.sh 2>/dev/null || java -jar /usr/share/jenkins/jenkins.war --httpPort=8080"
user=jenkins
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
environment=JENKINS_HOME="/var/jenkins_home",HOME="/var/jenkins_home",JAVA_HOME="/usr/local/openjdk-8"
