[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:elasticsearch]
command=/bin/bash -c "/usr/share/elasticsearch/bin/elasticsearch"
user=elasticsearch
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
environment=HOME="/usr/share/elasticsearch",ES_HOME="/usr/share/elasticsearch"
